### ISSUE TITLE
UML Story

### ISSUE THREAD

**Issue by DrewLetvin** [mikezhan88/Rate-My-Club#9]
## User Story
As a developer, I would like to create UML diagrams so that I can better understand app architecture and design.

## Detailed Description
Creation of UML diagrams (class, activity, sequence, state, use case) to flesh out the design of the application and provide insight into potential design and architecture patterns that could be used. Useful for informing future implementation and avoiding pitfalls of development down the road.

## Acceptance Criteria
- [ ] Given use cases, then the creation of accurate use case diagram
- [ ] Given typical user workflows, then the creation of accurate activity diagram
- [ ] Given use cases, then the creation of accurate state diagram
- [ ] Given typical user workflows, then the creation of accurate sequence diagram
- [ ] Given application architecture/structure, then the creation of accurate class diagram

**Comment by pranav-maddali** [comment]
closed - all diagrams uploaded
